export const HttpResponse = {
  OK: 'OK',
  SERVER_ERROR: 'Internal server Error!',
  USER_EXIST: 'User already exist',
  PAGE_NOT_FOUND: 'Page Not Found',
  USER_NOT_FOUND: 'User Not Found',
  INVALID_CREDENTIALS: 'Invalid Credentials',
  NO_TOKEN: 'Token Not Provided',
  OTP_INCORRECT: 'Incorrect OTP , try again',
  OTP_RESEND_SUCCESS: 'OTP Resend Successfully',
  OTP_EXPIRED: 'OTP Expired , Please Resend OTP',
  OTP_VERIFIED: 'OTP Verification Success',
  CREATED: 'Created Successfully',
  LOGGED_IN_SUCCESSFULLY: 'User Logged In Successfully',
  LOGGED_OUT: 'User Logged Out',
  USER_CREATION_FAILED: 'User Creation Failed',
  TOKEN_EXPIRED: 'Token Expired',
  RESET_LINK_SEND: 'Reset Password Sended To your Email , Check Your Mail',
  RESET_PASS_FAILED: 'Reset Password Failed',
  RESET_PASS_SUCCESS: 'Password Resetted Succesfully',
  IMAGE_NOT_PROVIDED: 'Please Provide a Image to upload',
  UPDATED: 'Updated Successfully',
  OLD_PASS_NOT_MATCHED:
    'Old Password you provided is incorrect , Try another one',
  USER_BLOCKED: 'You are Blocked By admin',
  ADDED_TO_GROUP: 'Added To Group',
  LEFT_GROUP: 'Left From group',
  RESOURCE_NOT_FOUND: 'Resource not found',
  ENTRY_RESTRICTED: 'Entry Restricted',
  UNAUTHORIZED: 'Unauthorized Access, Please Login First',
  CANNOT_UPDATE_LIVE_SESSION: ' You Cannot the datas of session which is live!',
  NOT_CREATER_OF_SESSION: 'Only Creater Can update the Session Data',
  ENDED_SESSION: 'This Session Already Ended And its Data is Recorded !',
  SESSION_ID_NOT_PROVIDED: 'Invalid Session ID',
  NO_CONTENT_FOR_PDF: 'No Content in Your Pdf',
  PAYMENT_FAILED : 'Payment Transaction Failed',
  USER_ALREADY_HAVE_AN_ACTIVE_PLAN : 'This is user have already a Active Plan',
  MONGO_URL_NOT_DEFINED_IN_ENV:'MONGO_URI is not defined in the environment variables.',
  GRIDFS_NOT_INITIATED:'GridFSBucket not initialized. Ensure MongoDB is connected.',
  CODE_TITLE_ALREADY_EXIST:'Code Snippet With This Title Already Exist on your Resources.Try Another One',
  INVALID_SESSION_CODE:'Invalid Session Code',
  NO_IMAGE :'No Profile Picture'
};
